### ISSUE TITLE
Context menu (share, copy, search) doesn't work

### ISSUE THREAD

**Issue by merlin-zaraza** [Adventech/sabbath-school-android#81]
Context menu (share, copy, search) doesn't work in next case:

1. Select text and make some highlight.
2. Select highlighted text by one tap.
3. Use share, copy or search

Result: Nothing shared, copied or searched.

**Comment by imasaru** [comment]
Reproducible? It works for me (video):

[![Google Drive](https://lh5.googleusercontent.com/5A-RVESI6Vg7OPU4dE5Fyb7cUA8WC_V54cDFasrAAh1NXnaRPFd40HC7xhxXUXPWoiPWtM4uthbFAx9MW07h=w1920-h1080-n-k-rw)](https://drive.google.com/open?id=1DOsOG7kNxwR-ZPDPx0GvnALWXDGbpzsG)

@merlin-zaraza Maybe try posting a screen recording of the issue? What version of Android are you using?

**Comment by VitalikL** [comment]
I can reproduce on my end. @imasaru are you doing a single tap (without holding)?

**Comment by imasaru** [comment]
@VitalikL Whoops. I totally missed that in his 2nd step. I was tapping and holding, sorry 😓

EDIT: I can reproduce it. So is the issue with the text not being highlighted? When I single-tap a highlighted text block, I can select to share, highlight, etc. but no text is selected, so nothing happens.

**Comment by VitalikL** [comment]
@merlin-zaraza @imasaru @TinasheMzondiwa I can also reproduce. This is interesting issue as technically nothing is "selected", but I guess we can find a workaround by asking WebView to give us the selection content. I will look into `sabbath-school-reader` to add this functionality

**Comment by charlykno64** [comment]
Hi @VitalikL, Can I help you? 

I think that we can receive the value from SSReadingView an ViewModel to this function in ss-reader.js

`    copy: function(**highlightId**){
      //evaluate parameter...
      SSBridge.onCopy(window.getSelection().toString());
      this.clearSelection();
    },`

Then we can evaluate it if(highlightId > 0) and then retrieve the string value for copy, search and share operations otherwise (else) we can use the current behavior.

This is only an untested idea because I cant pass this error: `com.pspdfkit.exceptions.InvalidPSPDFKitLicenseException: licenseKey must be a valid license key or null for trial mode.`
